name: pr

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        name: Toolchain
        with:
          profile: minimal
          toolchain: stable

      - run: cargo check

      - run: cargo test
