name: release

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: linux-x86_64
            exe: jwl
          - os: macos-latest
            name: macos-arm64
            exe: jwl
    steps:

    - uses: actions/checkout@v3
      name: Checkout

    - uses: actions-rs/toolchain@v1
      name: Toolchain
      with:
        profile: minimal
        toolchain: stable

    - uses: actions-rs/cargo@v1
      name: Compile
      with:
        command: build
        args: --release

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.name }}
        path: target/release/${{ matrix.exe }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build
    steps:

      - name: Download Linux x64
        uses: actions/download-artifact@v2
        with:
          name: linux-x64
          path: release

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            release/*
