name: release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: linux-x86_64
            exe: change-scribe
          - os: macos-latest
            name: macos-arm64
            exe: change-scribe
    steps:

    - uses: actions/checkout@v4

    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - run: cargo build --release

    - run: mv target/release/${{ matrix.exe }} ${{ matrix.exe }}-${{ matrix.name }}

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: ${{ matrix.exe }}-${{ matrix.name }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: write
    steps:

      - uses: actions/download-artifact@v4
        with:
          name: linux-x86_64
          path: release

      - uses: actions/download-artifact@v4
        with:
          name: macos-arm64
          path: release

      - uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            release/*
